### PR TITLE
Added CV Template! 

### PR DESCRIPTION
**Pull request by Piyush-Chandel7**
Hi @akshat3113 I added a CV template in the repository. Do check it and merge.

### CODE REVIEW

**Comment by Piyush-Chandel7** [comment]
Here's the image of CV template, which I've added!

**Comment by Piyush-Chandel7** [comment]
Here's the image of CV template, which I've added!

unknown

**Comment by akshat3113** [comment]
Nice work @Piyush-Chandel7 !

**Comment by akshat3113** [comment]
Nice work @Piyush-Chandel7 !

**Pull request merged**
